apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microservices
resources:
    - namespace.yaml
    - mongo-secret.yaml
    - cart-service
    - front-end
    - product-service
    - user-service