apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: microservices
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3R1b25nOjEyMzQ1Njc4OUA0NC4yMDEuMTU1LjQ5OjI3MDE3L3Byb2R1Y3Rfc2VydmljZT9hdXRoU291cmNlPWFkbWlu
  ACCESS_TOKEN: c3VwZXJzZWNyZXRhY2Nlc3N0b2tlbg==
