apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: microservices
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL3R1b25nOjEyMzQ1Njc4OUAxMy4yMjEuMTE0LjIwNzoyNzAxNy9wcm9kdWN0X3NlcnZpY2U/YXV0aFNvdXJjZT1hZG1pbg==
  ACCESS_TOKEN: c3VwZXJzZWNyZXRhY2Nlc3N0b2tlbg==
