apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  rules:
  - host: game-store.com
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
